/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    './src/pages/auth/Register.tsx'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#eaf1ff',
        'surface-bright': '#f8f9ff',
        'on-primary-container': '#dad7ff',
        'surface-container': '#e5eeff',
        'on-primary': '#ffffff',
        'surface-variant': '#d3e4fe',
        'primary-container': '#4f46e5',
        secondary: '#58579b',
        surface: '#f8f9ff',
        'primary-fixed-dim': '#c3c0ff',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#7b2f00',
        error: '#ba1a1a',
        'surface-container-high': '#dce9ff',
        'on-secondary-fixed-variant': '#413f82',
        'primary-fixed': '#e2dfff',
        'on-surface': '#0b1c30',
        'on-tertiary-container': '#ffd2be',
        'tertiary-fixed-dim': '#ffb695',
        background: '#f8f9ff',
        'outline-variant': '#c7c4d8',
        'on-secondary-container': '#454386',
        'surface-container-low': '#eff4ff',
        'on-background': '#0b1c30',
        'on-secondary-fixed': '#140f54',
        primary: '#3525cd',
        'inverse-surface': '#213145',
        'on-error-container': '#93000a',
        'on-surface-variant': '#464555',
        'error-container': '#ffdad6',
        tertiary: '#7e3000',
        'on-secondary': '#ffffff',
        'tertiary-container': '#a44100',
        'on-error': '#ffffff',
        'inverse-primary': '#c3c0ff',
        'on-primary-fixed-variant': '#3323cc',
        'surface-container-lowest': '#ffffff',
        outline: '#777587',
        'surface-dim': '#cbdbf5',
        'secondary-fixed': '#e2dfff',
        'surface-container-highest': '#d3e4fe',
        'tertiary-fixed': '#ffdbcc',
        'surface-tint': '#4d44e3',
        'on-tertiary-fixed': '#351000',
        'secondary-container': '#b6b4ff',
        'on-primary-fixed': '#0f0069',
        'secondary-fixed-dim': '#c3c0ff',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};